# Generated by Django 2.2.2 on 2019-08-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=220)),
                ('shortcode', models.CharField(max_length=15, unique=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('criado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
