# Generated by Django 2.2.2 on 2019-08-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encurtador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='shortcode',
            field=models.CharField(default='shortcodepadrao', max_length=15),
            preserve_default=False,
        ),
    ]
